# Generated by Django 4.1.7 on 2023-03-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0004_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='longitude',
            new_name='longitudee',
        ),
    ]
